<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="7" failures="0" skipped="0" tests="7" time="0.876" timestamp="2025-05-14T09:11:36.331011+02:00" hostname="debian"><testcase classname="" name="tests.test_categorie_age" time="0.000"><error message="collection failure">.venv/lib/python3.11/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
.venv/lib/python3.11/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1206: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1178: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1149: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
.venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:185: in exec_module
    exec(co, module.__dict__)
tests/test_categorie_age.py:6: in &lt;module&gt;
    from src.main import categorie_age
E     File "/home/malek/BRIEFS DEV IA/10.CI_CD/src/main.py", line 216
E       returnn pipeline
E               ^^^^^^^^
E   SyntaxError: invalid syntax</error></testcase><testcase classname="" name="tests.test_categorie_bmi" time="0.000"><error message="collection failure">.venv/lib/python3.11/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
.venv/lib/python3.11/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1206: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1178: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1149: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
.venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:185: in exec_module
    exec(co, module.__dict__)
tests/test_categorie_bmi.py:6: in &lt;module&gt;
    from src.main import categorie_bmi
E     File "/home/malek/BRIEFS DEV IA/10.CI_CD/src/main.py", line 216
E       returnn pipeline
E               ^^^^^^^^
E   SyntaxError: invalid syntax</error></testcase><testcase classname="" name="tests.test_charger_donnees" time="0.000"><error message="collection failure">.venv/lib/python3.11/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
.venv/lib/python3.11/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1206: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1178: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1149: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
.venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:185: in exec_module
    exec(co, module.__dict__)
tests/test_charger_donnees.py:7: in &lt;module&gt;
    from src.main import charger_donnees
E     File "/home/malek/BRIEFS DEV IA/10.CI_CD/src/main.py", line 216
E       returnn pipeline
E               ^^^^^^^^
E   SyntaxError: invalid syntax</error></testcase><testcase classname="" name="tests.test_creer_pipeline" time="0.000"><error message="collection failure">.venv/lib/python3.11/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
.venv/lib/python3.11/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1206: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1178: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1149: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
.venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:185: in exec_module
    exec(co, module.__dict__)
tests/test_creer_pipeline.py:11: in &lt;module&gt;
    from src.main import creer_pipeline, Preprocessor_Personnalise
E     File "/home/malek/BRIEFS DEV IA/10.CI_CD/src/main.py", line 216
E       returnn pipeline
E               ^^^^^^^^
E   SyntaxError: invalid syntax</error></testcase><testcase classname="" name="tests.test_metriques" time="0.000"><error message="collection failure">.venv/lib/python3.11/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
.venv/lib/python3.11/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1206: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1178: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1149: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
.venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:185: in exec_module
    exec(co, module.__dict__)
tests/test_metriques.py:7: in &lt;module&gt;
    from src.main import charger_donnees, charger_modele, metriques
E     File "/home/malek/BRIEFS DEV IA/10.CI_CD/src/main.py", line 216
E       returnn pipeline
E               ^^^^^^^^
E   SyntaxError: invalid syntax</error></testcase><testcase classname="" name="tests.test_prediciton" time="0.000"><error message="collection failure">.venv/lib/python3.11/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
.venv/lib/python3.11/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1206: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1178: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1149: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
.venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:185: in exec_module
    exec(co, module.__dict__)
tests/test_prediciton.py:7: in &lt;module&gt;
    from src.main import creer_exporter_modele, charger_modele, prediction
E     File "/home/malek/BRIEFS DEV IA/10.CI_CD/src/main.py", line 216
E       returnn pipeline
E               ^^^^^^^^
E   SyntaxError: invalid syntax</error></testcase><testcase classname="" name="tests.test_preprocessor_personnalise" time="0.000"><error message="collection failure">.venv/lib/python3.11/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
.venv/lib/python3.11/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1206: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1178: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1149: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
.venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:185: in exec_module
    exec(co, module.__dict__)
tests/test_preprocessor_personnalise.py:6: in &lt;module&gt;
    from src.main import Preprocessor_Personnalise
E     File "/home/malek/BRIEFS DEV IA/10.CI_CD/src/main.py", line 216
E       returnn pipeline
E               ^^^^^^^^
E   SyntaxError: invalid syntax</error></testcase></testsuite></testsuites>